export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        surface: 'var(--surface)',
        subtleSurface: 'var(--subtle-surface)',
        text: 'var(--text)',
        subtleText: 'var(--subtle-text)',
        border: 'var(--border)',
        primary: 'var(--primary)',
        primaryHover: 'var(--primary-hover)',
        secondary: 'var(--secondary)',
        secondaryHover: 'var(--secondary-hover)',
        info: 'var(--info)',
        infoBorder: 'var(--info-border)',
        warning: 'var(--warning)',
        warningBorder: 'var(--warning-border)',
        error: 'var(--error)',
        errorBorder: 'var(--error-border)',
        success: 'var(--success)',
        successBorder: 'var(--success-border)',
        link: 'var(--link)',
        linkHover: 'var(--link-hover)',
      },
      spacing: {
        '2xs': 'var(--space-2xs)',
        xs: 'var(--space-xs)',
        sm: 'var(--space-sm)',
        md: 'var(--space-md)',
        lg: 'var(--space-lg)',
        xl: 'var(--space-xl)',
        '2xl': 'var(--space-2xl)',
        '3xl': 'var(--space-3xl)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        sm: 'var(--radius-small)',
        md: 'var(--radius-medium)',
        lg: 'var(--radius-large)',
      },
      borderWidth: {
        none: 'var(--border-none)',
        hair: 'var(--border-hair)',
        thin: 'var(--border-thin)',
      },
      fontSize: {
        h1: ['var(--font-size-h1)', { lineHeight: 'var(--line-height-h1)' }],
        h2: ['var(--font-size-h2)', { lineHeight: 'var(--line-height-h2)' }],
        h3: ['var(--font-size-h3)', { lineHeight: 'var(--line-height-h3)' }],
        h4: ['var(--font-size-h4)', { lineHeight: 'var(--line-height-h4)' }],
        h5: ['var(--font-size-h5)', { lineHeight: 'var(--line-height-h5)' }],
        h6: ['var(--font-size-h6)', { lineHeight: 'var(--line-height-h6)' }],
        bodyLarge: ['var(--font-size-body-large)', { lineHeight: 'var(--line-height-body-large)' }],
        bodyBase: ['var(--font-size-body-base)', { lineHeight: 'var(--line-height-body-base)' }],
        bodySmall: ['var(--font-size-body-small)', { lineHeight: 'var(--line-height-body-small)' }],
        meta: ['var(--font-size-meta)', { lineHeight: 'var(--line-height-meta)' }],
        'meta-small': ['var(--font-size-meta-small)', { lineHeight: 'var(--line-height-meta-small)' }],
        link: ['var(--font-size-link)', { lineHeight: 'var(--line-height-link)' }],
        codeInline: ['var(--font-size-code-inline)', { lineHeight: 'var(--line-height-code-inline)' }],
        codeBlock: ['var(--font-size-code-block)', { lineHeight: 'var(--line-height-code-block)' }],
      },
      lineHeight: {
        h1: 'var(--line-height-h1)',
        h2: 'var(--line-height-h2)',
        h3: 'var(--line-height-h3)',
        h4: 'var(--line-height-h4)',
        h5: 'var(--line-height-h5)',
        h6: 'var(--line-height-h6)',
        bodyLarge: 'var(--line-height-body-large)',
        bodyBase: 'var(--line-height-body-base)',
        bodySmall: 'var(--line-height-body-small)',
        meta: 'var(--line-height-meta)',
        'meta-small': 'var(--line-height-meta-small)',
        link: 'var(--line-height-link)',
        codeInline: 'var(--line-height-code-inline)',
        codeBlock: 'var(--line-height-code-block)',
      },
      fontWeight: {
        heading: 'var(--font-weight-heading)',
        body: 'var(--font-weight-body)',
        meta: 'var(--font-weight-meta)',
        code: 'var(--font-weight-code)',
      },
      maxWidth: {
        'layout-text': 'var(--layout-text)',
        'layout-wide': 'var(--layout-wide)',
        'layout-max': 'var(--layout-max)',
      },
      fontFamily: {
        body: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'sans-serif'],
        heading: ['Fraunces', 'Georgia', 'serif'],
        code: ['JetBrains Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
      },
    },
  },
  plugins: [],
};
